run:
  skip-files:
  - "pkg/util/static/resource.go" # generated file

issues:
  exclude-use-default: false

linters:
  disable-all: true
  enable:
  - govet
  - errcheck
  - staticcheck
  - unused
  - gosimple
  - bodyclose
  - noctx
  - golint
  - gosec
  - unconvert
  - goconst
  - gocyclo
  - gofmt
  - goimports
  - misspell
  - lll
  - prealloc

linters-settings:
  govet:
    check-shadowing: true
    settings:
      printf:
        funcs:
        - (github.com/sirupsen/logrus.Logger).Infof
        - (github.com/sirupsen/logrus.Logger).Warnf
        - (github.com/sirupsen/logrus.Logger).Errorf
        - (github.com/sirupsen/logrus.Logger).Fatalf

  errcheck:
    check-type-assertions: true
    check-blank: true

  goconst:
    min-len: 2
    min-occurrences: 4

  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/sdslabs/allot

  misspell:
    locale: US
    ignore-words: []

  lll:
    line-length: 120
    tab-width: 4

  gocyclo:
    min-complexity: 20
